repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: run-unit-tests
        name: Run Unit Tests with unittest
        entry: python -m unittest discover -s tests -p "*.py"
        language: system
        types: [python]
        always_run: true
        pass_filenames: false
