repos:
  - repo: local
    hooks:
      - id: run-unit-tests
        name: Run Unit Tests with unittest
        entry: python -m unittest discover -s tests -p "*.py"
        language: system
        types: [python]
        always_run: true
        pass_filenames: false

