import os

from dotenv import load_dotenv

load_dotenv()

LINKEDIN_CSRF_TOKEN = os.environ["LINKEDIN_CSRF_TOKEN"]
LINKEDIN_COOKIE = os.environ["LINKEDIN_COOKIE"]

BING_SEARCH_API_KEY = os.getenv("BING_SEARCH_API_KEY")

GOOGLE_SEARCH_API_KEY = os.getenv("GOOGLE_SEARCH_API_KEY")
GOOGLE_SEARCH_CUSTOM_SEARCH_ENGINE_ID = os.getenv(
    "GOOGLE_SEARCH_CUSTOM_SEARCH_ENGINE_ID"
)

GOOGLE_GEMINI_API_KEY = os.getenv("GOOGLE_GEMINI_API_KEY")
GOOGLE_GEMINI_LLM_MODEL = os.getenv("GOOGLE_GEMINI_LLM_MODEL")

GMAIL_USERNAME = os.getenv("GMAIL_USERNAME")
GMAIL_PASSWORD = os.getenv("GMAIL_PASSWORD")

ENV = os.environ["ENV"]
IS_PROD = ENV == "prod"
IS_NON_PROD = ENV != "prod"

RESUME_LINK = os.getenv("RESUME_LINK")
FEEDBACK_EMAIL = os.getenv("FEEDBACK_EMAIL")
